<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Karapokotany extends \Entities\Karapokotany implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLaharana()
    {
        $this->__load();
        return parent::getLaharana();
    }

    public function setLaharana($laharana)
    {
        $this->__load();
        return parent::setLaharana($laharana);
    }

    public function getInscription()
    {
        $this->__load();
        return parent::getInscription();
    }

    public function setInscription($inscription)
    {
        $this->__load();
        return parent::setInscription($inscription);
    }

    public function getLohampianakaviana()
    {
        $this->__load();
        return parent::getLohampianakaviana();
    }

    public function setLohampianakaviana(\Entities\Olona $lohampianakaviana)
    {
        $this->__load();
        return parent::setLohampianakaviana($lohampianakaviana);
    }

    public function getFaritra()
    {
        $this->__load();
        return parent::getFaritra();
    }

    public function setFaritra($faritra)
    {
        $this->__load();
        return parent::setFaritra($faritra);
    }

    public function getNahatongavana()
    {
        $this->__load();
        return parent::getNahatongavana();
    }

    public function setNahatongavana($nahatongavana)
    {
        $this->__load();
        return parent::setNahatongavana($nahatongavana);
    }

    public function getNialana()
    {
        $this->__load();
        return parent::getNialana();
    }

    public function setNialana($nialana)
    {
        $this->__load();
        return parent::setNialana($nialana);
    }

    public function getAdiresy()
    {
        $this->__load();
        return parent::getAdiresy();
    }

    public function setAdiresy($adiresy)
    {
        $this->__load();
        return parent::setAdiresy($adiresy);
    }

    public function getBirao()
    {
        $this->__load();
        return parent::getBirao();
    }

    public function setBirao($birao)
    {
        $this->__load();
        return parent::setBirao($birao);
    }

    public function getNiaviana()
    {
        $this->__load();
        return parent::getNiaviana();
    }

    public function setNiaviana($niaviana)
    {
        $this->__load();
        return parent::setNiaviana($niaviana);
    }

    public function getAndehanana()
    {
        $this->__load();
        return parent::getAndehanana();
    }

    public function setAndehanana($andehanana)
    {
        $this->__load();
        return parent::setAndehanana($andehanana);
    }

    public function getOlonas()
    {
        $this->__load();
        return parent::getOlonas();
    }

    public function addOlona(\Entities\Olona $olona)
    {
        $this->__load();
        return parent::addOlona($olona);
    }

    public function addOlonas(\Doctrine\Common\Collections\ArrayCollection $olonas)
    {
        $this->__load();
        return parent::addOlonas($olonas);
    }

    public function removeOlonas(\Doctrine\Common\Collections\ArrayCollection $olonas)
    {
        $this->__load();
        return parent::removeOlonas($olonas);
    }

    public function getAdidies()
    {
        $this->__load();
        return parent::getAdidies();
    }

    public function addAdidy(\Entities\Adidy $adidy)
    {
        $this->__load();
        return parent::addAdidy($adidy);
    }

    public function addAdidies(\Doctrine\Common\Collections\ArrayCollection $adidies)
    {
        $this->__load();
        return parent::addAdidies($adidies);
    }

    public function removeAdidies(\Doctrine\Common\Collections\ArrayCollection $adidies)
    {
        $this->__load();
        return parent::removeAdidies($adidies);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'laharana', 'inscription', 'faritra', 'nahatongavana', 'nialana', 'adiresy', 'lohampianakaviana', 'birao', 'niaviana', 'andehanana', 'olonas', 'adidies');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}